/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/chemicals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    Search?: string;
                    CropId?: string;
                    WarehouseId?: string;
                    SortBy?: components["schemas"]["ChemicalSortBy"];
                    SortDirection?: components["schemas"]["SortDirection"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ChemicalListItemDto"][];
                        "application/json": components["schemas"]["ChemicalListItemDto"][];
                        "text/json": components["schemas"]["ChemicalListItemDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateChemicalRequest"];
                    "text/json": components["schemas"]["CreateChemicalRequest"];
                    "application/*+json": components["schemas"]["CreateChemicalRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ChemicalDetailDto"];
                        "application/json": components["schemas"]["ChemicalDetailDto"];
                        "text/json": components["schemas"]["ChemicalDetailDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chemicals/duplicates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    name?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["DuplicateDto"][];
                        "application/json": components["schemas"]["DuplicateDto"][];
                        "text/json": components["schemas"]["DuplicateDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chemicals/archived": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ArchivedChemicalDto"][];
                        "application/json": components["schemas"]["ArchivedChemicalDto"][];
                        "text/json": components["schemas"]["ArchivedChemicalDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chemicals/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ChemicalDetailDto"];
                        "application/json": components["schemas"]["ChemicalDetailDto"];
                        "text/json": components["schemas"]["ChemicalDetailDto"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateChemicalRequest"];
                    "text/json": components["schemas"]["UpdateChemicalRequest"];
                    "application/*+json": components["schemas"]["UpdateChemicalRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ChemicalDetailDto"];
                        "application/json": components["schemas"]["ChemicalDetailDto"];
                        "text/json": components["schemas"]["ChemicalDetailDto"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chemicals/{id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ArchiveChemicalRequest"];
                    "text/json": components["schemas"]["ArchiveChemicalRequest"];
                    "application/*+json": components["schemas"]["ArchiveChemicalRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chemicals/{id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chemicals/merge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["MergeChemicalsRequest"];
                    "text/json": components["schemas"]["MergeChemicalsRequest"];
                    "application/*+json": components["schemas"]["MergeChemicalsRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ChemicalDetailDto"];
                        "application/json": components["schemas"]["ChemicalDetailDto"];
                        "text/json": components["schemas"]["ChemicalDetailDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/crops": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CropDto"][];
                        "application/json": components["schemas"]["CropDto"][];
                        "text/json": components["schemas"]["CropDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateCropRequest"];
                    "text/json": components["schemas"]["CreateCropRequest"];
                    "application/*+json": components["schemas"]["CreateCropRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CropDto"];
                        "application/json": components["schemas"]["CropDto"];
                        "text/json": components["schemas"]["CropDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/crops/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateCropRequest"];
                    "text/json": components["schemas"]["UpdateCropRequest"];
                    "application/*+json": components["schemas"]["UpdateCropRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CropDto"];
                        "application/json": components["schemas"]["CropDto"];
                        "text/json": components["schemas"]["CropDto"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health/database": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health/backups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/warehouses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["WarehouseDto"][];
                        "application/json": components["schemas"]["WarehouseDto"][];
                        "text/json": components["schemas"]["WarehouseDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateWarehouseRequest"];
                    "text/json": components["schemas"]["CreateWarehouseRequest"];
                    "application/*+json": components["schemas"]["CreateWarehouseRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["WarehouseDto"];
                        "application/json": components["schemas"]["WarehouseDto"];
                        "text/json": components["schemas"]["WarehouseDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/warehouses/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateWarehouseRequest"];
                    "text/json": components["schemas"]["UpdateWarehouseRequest"];
                    "application/*+json": components["schemas"]["UpdateWarehouseRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["WarehouseDto"];
                        "application/json": components["schemas"]["WarehouseDto"];
                        "text/json": components["schemas"]["WarehouseDto"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ArchiveChemicalRequest: {
            confirmation?: string | null;
        };
        ArchivedChemicalDto: {
            /** Format: uuid */
            id?: string;
            name?: string | null;
            manufacturer?: string | null;
            crops?: components["schemas"]["CropRefDto"][] | null;
            /** Format: double */
            totalLiters?: number;
            /** Format: date-time */
            archivedAt?: string;
        };
        ChemicalDetailDto: {
            /** Format: uuid */
            id?: string;
            name?: string | null;
            manufacturer?: string | null;
            comment?: string | null;
            status?: components["schemas"]["ItemStatus"];
            /** Format: uuid */
            mergedIntoItemId?: string | null;
            crops?: components["schemas"]["CropRefDto"][] | null;
            /** Format: double */
            totalLiters?: number;
            warehouses?: components["schemas"]["WarehouseStockDto"][] | null;
        };
        ChemicalListItemDto: {
            /** Format: uuid */
            id?: string;
            name?: string | null;
            /** Format: double */
            totalLiters?: number;
            crops?: components["schemas"]["CropRefDto"][] | null;
            stockStatus?: components["schemas"]["StockStatus"];
        };
        /**
         * Format: int32
         * @enum {integer}
         */
        ChemicalSortBy: 0 | 1 | 2 | 3;
        CreateChemicalRequest: {
            name?: string | null;
            manufacturer?: string | null;
            comment?: string | null;
            cropIds?: string[] | null;
        };
        CreateCropRequest: {
            name?: string | null;
        };
        CreateWarehouseRequest: {
            number?: string | null;
        };
        CropDto: {
            /** Format: uuid */
            id?: string;
            name?: string | null;
        };
        CropRefDto: {
            /** Format: uuid */
            id?: string;
            name?: string | null;
        };
        DuplicateDto: {
            /** Format: uuid */
            id?: string;
            name?: string | null;
            manufacturer?: string | null;
        };
        /**
         * Format: int32
         * @enum {integer}
         */
        ItemStatus: 1 | 2 | 3;
        MergeChemicalsRequest: {
            /** Format: uuid */
            targetId?: string;
            sourceIds?: string[] | null;
            manufacturer?: string | null;
            comment?: string | null;
            cropIds?: string[] | null;
        };
        OpenedPackageDto: {
            /** Format: uuid */
            id?: string;
            unitType?: components["schemas"]["UnitType"];
            /** Format: double */
            initialLiters?: number;
            /** Format: double */
            remainingLiters?: number;
        };
        PackageGroupDto: {
            /** Format: uuid */
            id?: string;
            unitType?: components["schemas"]["UnitType"];
            /** Format: double */
            packageVolumeLiters?: number;
            /** Format: int32 */
            quantity?: number;
        };
        /**
         * Format: int32
         * @enum {integer}
         */
        SortDirection: 0 | 1;
        /**
         * Format: int32
         * @enum {integer}
         */
        StockStatus: 0 | 1 | 2;
        /**
         * Format: int32
         * @enum {integer}
         */
        UnitType: 1 | 2 | 3;
        UpdateChemicalRequest: {
            name?: string | null;
            manufacturer?: string | null;
            comment?: string | null;
            cropIds?: string[] | null;
        };
        UpdateCropRequest: {
            name?: string | null;
        };
        UpdateWarehouseRequest: {
            number?: string | null;
        };
        WarehouseDto: {
            /** Format: uuid */
            id?: string;
            number?: string | null;
        };
        WarehouseStockDto: {
            /** Format: uuid */
            warehouseId?: string;
            warehouseNumber?: string | null;
            /** Format: double */
            totalLiters?: number;
            /** Format: double */
            looseLiters?: number;
            packageGroups?: components["schemas"]["PackageGroupDto"][] | null;
            openedPackages?: components["schemas"]["OpenedPackageDto"][] | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
