/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/audit-log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    DateFrom?: string;
                    DateTo?: string;
                    Action?: components["schemas"]["AuditAction"];
                    EntityType?: string;
                    UserId?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AuditLogDto"][];
                        "application/json": components["schemas"]["AuditLogDto"][];
                        "text/json": components["schemas"]["AuditLogDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["BackupInfo"];
                        "application/json": components["schemas"]["BackupInfo"];
                        "text/json": components["schemas"]["BackupInfo"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backups/{fileName}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    fileName: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backups/{fileName}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    fileName: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["BackupRestoreResultDto"];
                        "application/json": components["schemas"]["BackupRestoreResultDto"];
                        "text/json": components["schemas"]["BackupRestoreResultDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chemicals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    Search?: string;
                    CropId?: string;
                    WarehouseId?: string;
                    SortBy?: components["schemas"]["ChemicalSortBy"];
                    SortDirection?: components["schemas"]["SortDirection"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ChemicalListItemDto"][];
                        "application/json": components["schemas"]["ChemicalListItemDto"][];
                        "text/json": components["schemas"]["ChemicalListItemDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateChemicalRequest"];
                    "text/json": components["schemas"]["CreateChemicalRequest"];
                    "application/*+json": components["schemas"]["CreateChemicalRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ChemicalDetailDto"];
                        "application/json": components["schemas"]["ChemicalDetailDto"];
                        "text/json": components["schemas"]["ChemicalDetailDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chemicals/duplicates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    name?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["DuplicateDto"][];
                        "application/json": components["schemas"]["DuplicateDto"][];
                        "text/json": components["schemas"]["DuplicateDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chemicals/archived": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ArchivedChemicalDto"][];
                        "application/json": components["schemas"]["ArchivedChemicalDto"][];
                        "text/json": components["schemas"]["ArchivedChemicalDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chemicals/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ChemicalDetailDto"];
                        "application/json": components["schemas"]["ChemicalDetailDto"];
                        "text/json": components["schemas"]["ChemicalDetailDto"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateChemicalRequest"];
                    "text/json": components["schemas"]["UpdateChemicalRequest"];
                    "application/*+json": components["schemas"]["UpdateChemicalRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ChemicalDetailDto"];
                        "application/json": components["schemas"]["ChemicalDetailDto"];
                        "text/json": components["schemas"]["ChemicalDetailDto"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chemicals/{id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ArchiveChemicalRequest"];
                    "text/json": components["schemas"]["ArchiveChemicalRequest"];
                    "application/*+json": components["schemas"]["ArchiveChemicalRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chemicals/{id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chemicals/merge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["MergeChemicalsRequest"];
                    "text/json": components["schemas"]["MergeChemicalsRequest"];
                    "application/*+json": components["schemas"]["MergeChemicalsRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ChemicalDetailDto"];
                        "application/json": components["schemas"]["ChemicalDetailDto"];
                        "text/json": components["schemas"]["ChemicalDetailDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/crops": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CropDto"][];
                        "application/json": components["schemas"]["CropDto"][];
                        "text/json": components["schemas"]["CropDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateCropRequest"];
                    "text/json": components["schemas"]["CreateCropRequest"];
                    "application/*+json": components["schemas"]["CreateCropRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CropDto"];
                        "application/json": components["schemas"]["CropDto"];
                        "text/json": components["schemas"]["CropDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/crops/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateCropRequest"];
                    "text/json": components["schemas"]["UpdateCropRequest"];
                    "application/*+json": components["schemas"]["UpdateCropRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CropDto"];
                        "application/json": components["schemas"]["CropDto"];
                        "text/json": components["schemas"]["CropDto"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["DashboardDto"];
                        "application/json": components["schemas"]["DashboardDto"];
                        "text/json": components["schemas"]["DashboardDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/export/chemicals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/export/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    DateFrom?: string;
                    DateTo?: string;
                    ChemicalId?: string;
                    MovementType?: components["schemas"]["MovementType"];
                    WarehouseId?: string;
                    CropId?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health/database": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health/backups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    DateFrom?: string;
                    DateTo?: string;
                    ChemicalId?: string;
                    MovementType?: components["schemas"]["MovementType"];
                    WarehouseId?: string;
                    CropId?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["HistoryItemDto"][];
                        "application/json": components["schemas"]["HistoryItemDto"][];
                        "text/json": components["schemas"]["HistoryItemDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/history/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["HistoryDetailDto"];
                        "application/json": components["schemas"]["HistoryDetailDto"];
                        "text/json": components["schemas"]["HistoryDetailDto"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["EditMovementRequest"];
                    "text/json": components["schemas"]["EditMovementRequest"];
                    "application/*+json": components["schemas"]["EditMovementRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inventory/income": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["IncomeRequest"];
                    "text/json": components["schemas"]["IncomeRequest"];
                    "application/*+json": components["schemas"]["IncomeRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["IncomeResultDto"];
                        "application/json": components["schemas"]["IncomeResultDto"];
                        "text/json": components["schemas"]["IncomeResultDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inventory/outcome/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["OutcomeRequest"];
                    "text/json": components["schemas"]["OutcomeRequest"];
                    "application/*+json": components["schemas"]["OutcomeRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["OutcomePreviewResponse"];
                        "application/json": components["schemas"]["OutcomePreviewResponse"];
                        "text/json": components["schemas"]["OutcomePreviewResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inventory/outcome": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["OutcomeRequest"];
                    "text/json": components["schemas"]["OutcomeRequest"];
                    "application/*+json": components["schemas"]["OutcomeRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["OutcomeResultDto"];
                        "application/json": components["schemas"]["OutcomeResultDto"];
                        "text/json": components["schemas"]["OutcomeResultDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inventory/correction/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CorrectionRequest"];
                    "text/json": components["schemas"]["CorrectionRequest"];
                    "application/*+json": components["schemas"]["CorrectionRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CorrectionPreviewResponse"];
                        "application/json": components["schemas"]["CorrectionPreviewResponse"];
                        "text/json": components["schemas"]["CorrectionPreviewResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inventory/correction": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CorrectionRequest"];
                    "text/json": components["schemas"]["CorrectionRequest"];
                    "application/*+json": components["schemas"]["CorrectionRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CorrectionResultDto"];
                        "application/json": components["schemas"]["CorrectionResultDto"];
                        "text/json": components["schemas"]["CorrectionResultDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inventory/check-sheet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    warehouseId?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["InventoryCheckSheetDto"];
                        "application/json": components["schemas"]["InventoryCheckSheetDto"];
                        "text/json": components["schemas"]["InventoryCheckSheetDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inventory/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["InventoryCheckRequest"];
                    "text/json": components["schemas"]["InventoryCheckRequest"];
                    "application/*+json": components["schemas"]["InventoryCheckRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["InventoryCheckResultDto"];
                        "application/json": components["schemas"]["InventoryCheckResultDto"];
                        "text/json": components["schemas"]["InventoryCheckResultDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AppSettingsDto"];
                        "application/json": components["schemas"]["AppSettingsDto"];
                        "text/json": components["schemas"]["AppSettingsDto"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateSettingsRequest"];
                    "text/json": components["schemas"]["UpdateSettingsRequest"];
                    "application/*+json": components["schemas"]["UpdateSettingsRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AppSettingsDto"];
                        "application/json": components["schemas"]["AppSettingsDto"];
                        "text/json": components["schemas"]["AppSettingsDto"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/warehouses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["WarehouseDto"][];
                        "application/json": components["schemas"]["WarehouseDto"][];
                        "text/json": components["schemas"]["WarehouseDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateWarehouseRequest"];
                    "text/json": components["schemas"]["CreateWarehouseRequest"];
                    "application/*+json": components["schemas"]["CreateWarehouseRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["WarehouseDto"];
                        "application/json": components["schemas"]["WarehouseDto"];
                        "text/json": components["schemas"]["WarehouseDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/warehouses/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateWarehouseRequest"];
                    "text/json": components["schemas"]["UpdateWarehouseRequest"];
                    "application/*+json": components["schemas"]["UpdateWarehouseRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["WarehouseDto"];
                        "application/json": components["schemas"]["WarehouseDto"];
                        "text/json": components["schemas"]["WarehouseDto"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AppSettingsDto: {
            /** Format: double */
            lowStockThresholdLiters?: number;
            autoOpenPackages?: boolean;
            /** Format: date-time */
            updatedAt?: string;
        };
        ArchiveChemicalRequest: {
            confirmation?: string | null;
        };
        ArchivedChemicalDto: {
            /** Format: uuid */
            id?: string;
            name?: string | null;
            manufacturer?: string | null;
            crops?: components["schemas"]["CropRefDto"][] | null;
            /** Format: double */
            totalLiters?: number;
            /** Format: date-time */
            archivedAt?: string;
        };
        /**
         * Format: int32
         * @enum {integer}
         */
        AuditAction: 1 | 2 | 3 | 4 | 5 | 6;
        AuditLogDto: {
            /** Format: uuid */
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: uuid */
            userId?: string;
            userName?: string | null;
            action?: components["schemas"]["AuditAction"];
            entityType?: string | null;
            /** Format: uuid */
            entityId?: string;
            oldValues?: string | null;
            newValues?: string | null;
        };
        BackupInfo: {
            fileName?: string | null;
            /** Format: int64 */
            sizeBytes?: number;
            /** Format: date-time */
            createdAt?: string;
        };
        BackupRestoreResultDto: {
            /** Format: int32 */
            tablesRestored?: number;
            /** Format: int32 */
            rowsRestored?: number;
        };
        ChemicalDetailDto: {
            /** Format: uuid */
            id?: string;
            name?: string | null;
            manufacturer?: string | null;
            comment?: string | null;
            status?: components["schemas"]["ItemStatus"];
            /** Format: uuid */
            mergedIntoItemId?: string | null;
            crops?: components["schemas"]["CropRefDto"][] | null;
            /** Format: double */
            totalLiters?: number;
            warehouses?: components["schemas"]["WarehouseStockDto"][] | null;
        };
        ChemicalListItemDto: {
            /** Format: uuid */
            id?: string;
            name?: string | null;
            /** Format: double */
            totalLiters?: number;
            crops?: components["schemas"]["CropRefDto"][] | null;
            stockStatus?: components["schemas"]["StockStatus"];
        };
        /**
         * Format: int32
         * @enum {integer}
         */
        ChemicalSortBy: 0 | 1 | 2 | 3;
        /**
         * Format: int32
         * @enum {integer}
         */
        CorrectionMode: 0 | 1 | 2;
        CorrectionPreviewResponse: {
            /** Format: double */
            currentTotal?: number;
            /** Format: double */
            newTotal?: number;
            /** Format: double */
            delta?: number;
            isBigChange?: boolean;
            requiresDetailed?: boolean;
            message?: string | null;
        };
        CorrectionRequest: {
            /** Format: uuid */
            chemicalId?: string;
            /** Format: uuid */
            warehouseId?: string;
            mode?: components["schemas"]["CorrectionMode"];
            /** Format: double */
            actualTotalLiters?: number | null;
            /** Format: double */
            deltaLiters?: number | null;
            detailed?: components["schemas"]["DetailedInventoryDto"];
            confirmed?: boolean;
            /** Format: date-time */
            occurredAt?: string | null;
            comment?: string | null;
        };
        CorrectionResultDto: {
            /** Format: double */
            totalLiters?: number;
            /** Format: uuid */
            movementId?: string;
        };
        CreateChemicalRequest: {
            name?: string | null;
            manufacturer?: string | null;
            comment?: string | null;
            cropIds?: string[] | null;
        };
        CreateCropRequest: {
            name?: string | null;
        };
        CreateWarehouseRequest: {
            number?: string | null;
        };
        CropDto: {
            /** Format: uuid */
            id?: string;
            name?: string | null;
        };
        CropRefDto: {
            /** Format: uuid */
            id?: string;
            name?: string | null;
        };
        DashboardDto: {
            /** Format: int32 */
            activeChemicals?: number;
            /** Format: int32 */
            warehouses?: number;
            /** Format: int32 */
            emptyCount?: number;
            /** Format: int32 */
            lowCount?: number;
            /** Format: double */
            totalLiters?: number;
            /** Format: double */
            lowStockThresholdLiters?: number;
            empty?: components["schemas"]["DashboardStockDto"][] | null;
            low?: components["schemas"]["DashboardStockDto"][] | null;
            recentOperations?: components["schemas"]["HistoryItemDto"][] | null;
        };
        DashboardStockDto: {
            /** Format: uuid */
            chemicalId?: string;
            name?: string | null;
            /** Format: double */
            totalLiters?: number;
            status?: components["schemas"]["StockStatus"];
        };
        DetailedGroupDto: {
            unitType?: components["schemas"]["UnitType"];
            /** Format: double */
            packageVolumeLiters?: number;
            /** Format: int32 */
            quantity?: number;
        };
        DetailedInventoryDto: {
            /** Format: double */
            looseLiters?: number;
            groups?: components["schemas"]["DetailedGroupDto"][] | null;
            opened?: components["schemas"]["DetailedOpenedDto"][] | null;
        };
        DetailedOpenedDto: {
            unitType?: components["schemas"]["UnitType"];
            /** Format: double */
            initialLiters?: number;
            /** Format: double */
            remainingLiters?: number;
        };
        DuplicateDto: {
            /** Format: uuid */
            id?: string;
            name?: string | null;
            manufacturer?: string | null;
        };
        EditMovementRequest: {
            /** Format: date-time */
            occurredAt?: string | null;
            /** Format: uuid */
            cropId?: string | null;
            comment?: string | null;
            /** Format: double */
            quantityLiters?: number | null;
            unit?: components["schemas"]["UnitType"];
            /** Format: double */
            packageVolumeLiters?: number | null;
            /** Format: int32 */
            packagesQuantity?: number | null;
        };
        HistoryDetailDto: {
            /** Format: uuid */
            id?: string;
            /** Format: date-time */
            occurredAt?: string;
            movementType?: components["schemas"]["MovementType"];
            /** Format: uuid */
            chemicalId?: string;
            chemicalName?: string | null;
            /** Format: double */
            quantityLiters?: number;
            unitType?: components["schemas"]["UnitType"];
            /** Format: double */
            packageVolumeLiters?: number | null;
            /** Format: int32 */
            packagesQuantity?: number | null;
            /** Format: uuid */
            warehouseId?: string;
            warehouseNumber?: string | null;
            /** Format: uuid */
            cropId?: string | null;
            cropName?: string | null;
            comment?: string | null;
            sources?: components["schemas"]["HistoryDetailSourceDto"][] | null;
        };
        HistoryDetailSourceDto: {
            sourceType?: components["schemas"]["MovementSourceType"];
            unitType?: components["schemas"]["UnitType"];
            /** Format: double */
            packageVolumeLiters?: number | null;
            /** Format: double */
            quantityLiters?: number;
            /** Format: int32 */
            packagesQuantity?: number | null;
        };
        HistoryItemDto: {
            /** Format: uuid */
            id?: string;
            /** Format: date-time */
            occurredAt?: string;
            movementType?: components["schemas"]["MovementType"];
            /** Format: uuid */
            chemicalId?: string;
            chemicalName?: string | null;
            /** Format: double */
            quantityLiters?: number;
            /** Format: uuid */
            warehouseId?: string;
            warehouseNumber?: string | null;
            /** Format: uuid */
            cropId?: string | null;
            cropName?: string | null;
            comment?: string | null;
        };
        IncomeRequest: {
            /** Format: uuid */
            chemicalId?: string;
            /** Format: uuid */
            warehouseId?: string;
            unit?: components["schemas"]["UnitType"];
            /** Format: double */
            quantity?: number;
            /** Format: double */
            packageVolumeLiters?: number | null;
            /** Format: date-time */
            occurredAt?: string | null;
            comment?: string | null;
        };
        IncomeResultDto: {
            /** Format: double */
            totalLiters?: number;
            /** Format: uuid */
            movementId?: string;
        };
        InventoryCheckEntry: {
            /** Format: uuid */
            chemicalId?: string;
            /** Format: double */
            actualTotalLiters?: number;
        };
        InventoryCheckLineDto: {
            /** Format: uuid */
            chemicalId?: string;
            chemicalName?: string | null;
            /** Format: double */
            currentTotalLiters?: number;
            /** Format: double */
            looseLiters?: number;
            /** Format: int32 */
            fullPackages?: number;
            /** Format: int32 */
            openedPackages?: number;
        };
        InventoryCheckLineResult: {
            /** Format: uuid */
            chemicalId?: string;
            chemicalName?: string | null;
            /** Format: double */
            previousTotal?: number;
            /** Format: double */
            newTotal?: number;
            /** Format: double */
            delta?: number;
            outcome?: components["schemas"]["InventoryCheckOutcome"];
        };
        /**
         * Format: int32
         * @enum {integer}
         */
        InventoryCheckOutcome: 0 | 1 | 2;
        InventoryCheckRequest: {
            /** Format: uuid */
            warehouseId?: string;
            entries?: components["schemas"]["InventoryCheckEntry"][] | null;
            /** Format: date-time */
            occurredAt?: string | null;
            comment?: string | null;
        };
        InventoryCheckResultDto: {
            /** Format: int32 */
            appliedCount?: number;
            /** Format: int32 */
            unchangedCount?: number;
            /** Format: int32 */
            needsDetailedCount?: number;
            lines?: components["schemas"]["InventoryCheckLineResult"][] | null;
        };
        InventoryCheckSheetDto: {
            /** Format: uuid */
            warehouseId?: string;
            warehouseNumber?: string | null;
            lines?: components["schemas"]["InventoryCheckLineDto"][] | null;
        };
        /**
         * Format: int32
         * @enum {integer}
         */
        ItemStatus: 1 | 2 | 3;
        MergeChemicalsRequest: {
            /** Format: uuid */
            targetId?: string;
            sourceIds?: string[] | null;
            manufacturer?: string | null;
            comment?: string | null;
            cropIds?: string[] | null;
        };
        /**
         * Format: int32
         * @enum {integer}
         */
        MovementSourceType: 1 | 2 | 3;
        /**
         * Format: int32
         * @enum {integer}
         */
        MovementType: 1 | 2 | 3 | 4;
        OpenedPackageDto: {
            /** Format: uuid */
            id?: string;
            unitType?: components["schemas"]["UnitType"];
            /** Format: double */
            initialLiters?: number;
            /** Format: double */
            remainingLiters?: number;
        };
        OutcomePreviewResponse: {
            sufficient?: boolean;
            /** Format: double */
            requested?: number;
            /** Format: double */
            fulfilled?: number;
            /** Format: double */
            available?: number;
            willOpenNewPackage?: boolean;
            topUpUsed?: boolean;
            requiresOpenConfirmation?: boolean;
            steps?: components["schemas"]["OutcomeStepDto"][] | null;
        };
        OutcomeRequest: {
            /** Format: uuid */
            chemicalId?: string;
            /** Format: uuid */
            warehouseId?: string;
            /** Format: uuid */
            cropId?: string;
            /** Format: double */
            quantityLiters?: number;
            source?: components["schemas"]["OutcomeSourceDto"];
            allowOpenNewPackage?: boolean;
            /** Format: date-time */
            occurredAt?: string | null;
            comment?: string | null;
        };
        OutcomeResultDto: {
            /** Format: double */
            writtenOffLiters?: number;
            /** Format: double */
            totalLiters?: number;
            /** Format: uuid */
            movementId?: string;
        };
        OutcomeSourceDto: {
            type?: components["schemas"]["MovementSourceType"];
            /** Format: uuid */
            id?: string | null;
        };
        OutcomeStepDto: {
            sourceType?: components["schemas"]["MovementSourceType"];
            /** Format: uuid */
            sourceId?: string | null;
            unitType?: components["schemas"]["UnitType"];
            /** Format: double */
            packageVolumeLiters?: number | null;
            /** Format: double */
            liters?: number;
            /** Format: int32 */
            wholePackages?: number;
            /** Format: double */
            openedRemainder?: number;
            opensNewPackage?: boolean;
        };
        PackageGroupDto: {
            /** Format: uuid */
            id?: string;
            unitType?: components["schemas"]["UnitType"];
            /** Format: double */
            packageVolumeLiters?: number;
            /** Format: int32 */
            quantity?: number;
        };
        /**
         * Format: int32
         * @enum {integer}
         */
        SortDirection: 0 | 1;
        /**
         * Format: int32
         * @enum {integer}
         */
        StockStatus: 0 | 1 | 2;
        /**
         * Format: int32
         * @enum {integer}
         */
        UnitType: 1 | 2 | 3;
        UpdateChemicalRequest: {
            name?: string | null;
            manufacturer?: string | null;
            comment?: string | null;
            cropIds?: string[] | null;
        };
        UpdateCropRequest: {
            name?: string | null;
        };
        UpdateSettingsRequest: {
            /** Format: double */
            lowStockThresholdLiters?: number;
            autoOpenPackages?: boolean;
        };
        UpdateWarehouseRequest: {
            number?: string | null;
        };
        WarehouseDto: {
            /** Format: uuid */
            id?: string;
            number?: string | null;
        };
        WarehouseStockDto: {
            /** Format: uuid */
            warehouseId?: string;
            warehouseNumber?: string | null;
            /** Format: double */
            totalLiters?: number;
            /** Format: double */
            looseLiters?: number;
            packageGroups?: components["schemas"]["PackageGroupDto"][] | null;
            openedPackages?: components["schemas"]["OpenedPackageDto"][] | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
