// <auto-generated />
using System;
using AgroInventory.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AgroInventory.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AgroInventoryDbContext))]
    [Migration("20260715071134_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AgroInventory.Domain.Entities.AppSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AutoOpenPackages")
                        .HasColumnType("boolean")
                        .HasColumnName("auto_open_packages");

                    b.Property<decimal>("LowStockThresholdLiters")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("low_stock_threshold_liters");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_app_settings");

                    b.ToTable("app_settings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            AutoOpenPackages = false,
                            LowStockThresholdLiters = 10m,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("AgroInventory.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Action")
                        .HasColumnType("integer")
                        .HasColumnName("action");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_type");

                    b.Property<string>("NewValues")
                        .HasColumnType("jsonb")
                        .HasColumnName("new_values");

                    b.Property<string>("OldValues")
                        .HasColumnType("jsonb")
                        .HasColumnName("old_values");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("Action")
                        .HasDatabaseName("ix_audit_logs_action");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_audit_logs_created_at");

                    b.HasIndex("EntityType")
                        .HasDatabaseName("ix_audit_logs_entity_type");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_audit_logs_user_id");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("AgroInventory.Domain.Entities.ChemicalCrop", b =>
                {
                    b.Property<Guid>("ChemicalId")
                        .HasColumnType("uuid")
                        .HasColumnName("chemical_id");

                    b.Property<Guid>("CropId")
                        .HasColumnType("uuid")
                        .HasColumnName("crop_id");

                    b.HasKey("ChemicalId", "CropId")
                        .HasName("pk_chemical_crops");

                    b.HasIndex("CropId")
                        .HasDatabaseName("ix_chemical_crops_crop_id");

                    b.ToTable("chemical_crops", (string)null);
                });

            modelBuilder.Entity("AgroInventory.Domain.Entities.ChemicalDetails", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("comment");

                    b.Property<Guid>("InventoryItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("inventory_item_id");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("manufacturer");

                    b.Property<int?>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_chemical_details");

                    b.HasIndex("InventoryItemId")
                        .IsUnique()
                        .HasDatabaseName("ix_chemical_details_inventory_item_id");

                    b.ToTable("chemical_details", (string)null);
                });

            modelBuilder.Entity("AgroInventory.Domain.Entities.ChemicalStockBalance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChemicalId")
                        .HasColumnType("uuid")
                        .HasColumnName("chemical_id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<decimal>("LooseLiters")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("loose_liters");

                    b.Property<decimal>("TotalLiters")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("total_liters");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("warehouse_id");

                    b.HasKey("Id")
                        .HasName("pk_chemical_stock_balances");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_chemical_stock_balances_company_id");

                    b.HasIndex("WarehouseId")
                        .HasDatabaseName("ix_chemical_stock_balances_warehouse_id");

                    b.HasIndex("ChemicalId", "WarehouseId")
                        .IsUnique()
                        .HasDatabaseName("ix_chemical_stock_balances_chemical_id_warehouse_id");

                    b.ToTable("chemical_stock_balances", (string)null);
                });

            modelBuilder.Entity("AgroInventory.Domain.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("address");

                    b.Property<string>("BinOrInn")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("bin_or_inn");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("country");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("LegalName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("legal_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("timezone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_companies");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_companies_created_by_user_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_companies_status");

                    b.ToTable("companies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000201"),
                            Country = "KZ",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedByUserId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Name = "Хозяйство по умолчанию",
                            Status = 0,
                            Timezone = "Asia/Almaty",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("AgroInventory.Domain.Entities.CompanyMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_company_memberships");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_company_memberships_company_id");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_company_memberships_created_by_user_id");

                    b.HasIndex("UserId", "CompanyId")
                        .IsUnique()
                        .HasDatabaseName("ix_company_memberships_user_id_company_id");

                    b.ToTable("company_memberships", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000202"),
                            CompanyId = new Guid("00000000-0000-0000-0000-000000000201"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedByUserId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Role = 1,
                            Status = 0,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserId = new Guid("00000000-0000-0000-0000-000000000001")
                        });
                });

            modelBuilder.Entity("AgroInventory.Domain.Entities.Crop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_crops");

                    b.HasIndex("CompanyId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_crops_company_id_name");

                    b.ToTable("crops", (string)null);
                });

            modelBuilder.Entity("AgroInventory.Domain.Entities.Field", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("number");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_fields");

                    b.HasIndex("CompanyId", "Number")
                        .IsUnique()
                        .HasDatabaseName("ix_fields_company_id_number");

                    b.ToTable("fields", (string)null);
                });

            modelBuilder.Entity("AgroInventory.Domain.Entities.InventoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("ItemType")
                        .HasColumnType("integer")
                        .HasColumnName("item_type");

                    b.Property<Guid?>("MergedIntoItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("merged_into_item_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_inventory_items");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_inventory_items_company_id");

                    b.HasIndex("ItemType")
                        .HasDatabaseName("ix_inventory_items_item_type");

                    b.HasIndex("MergedIntoItemId")
                        .HasDatabaseName("ix_inventory_items_merged_into_item_id");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_inventory_items_name");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_inventory_items_status");

                    b.ToTable("inventory_items", (string)null);
                });

            modelBuilder.Entity("AgroInventory.Domain.Entities.InventoryMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChemicalId")
                        .HasColumnType("uuid")
                        .HasColumnName("chemical_id");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("comment");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<Guid?>("CropId")
                        .HasColumnType("uuid")
                        .HasColumnName("crop_id");

                    b.Property<Guid?>("FieldId")
                        .HasColumnType("uuid")
                        .HasColumnName("field_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<int>("MovementType")
                        .HasColumnType("integer")
                        .HasColumnName("movement_type");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<decimal?>("PackageVolumeLiters")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("package_volume_liters");

                    b.Property<int?>("PackagesQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("packages_quantity");

                    b.Property<decimal>("QuantityLiters")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("quantity_liters");

                    b.Property<int?>("UnitType")
                        .HasColumnType("integer")
                        .HasColumnName("unit_type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("warehouse_id");

                    b.HasKey("Id")
                        .HasName("pk_inventory_movements");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_inventory_movements_company_id");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_inventory_movements_created_by_user_id");

                    b.HasIndex("CropId")
                        .HasDatabaseName("ix_inventory_movements_crop_id");

                    b.HasIndex("FieldId")
                        .HasDatabaseName("ix_inventory_movements_field_id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_inventory_movements_is_deleted");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_inventory_movements_occurred_at");

                    b.HasIndex("WarehouseId")
                        .HasDatabaseName("ix_inventory_movements_warehouse_id");

                    b.HasIndex("ChemicalId", "WarehouseId")
                        .HasDatabaseName("ix_inventory_movements_chemical_id_warehouse_id");

                    b.ToTable("inventory_movements", (string)null);
                });

            modelBuilder.Entity("AgroInventory.Domain.Entities.InventoryMovementDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("MovementId")
                        .HasColumnType("uuid")
                        .HasColumnName("movement_id");

                    b.Property<decimal?>("PackageVolumeLiters")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("package_volume_liters");

                    b.Property<int?>("PackagesQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("packages_quantity");

                    b.Property<decimal>("QuantityLiters")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("quantity_liters");

                    b.Property<Guid?>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<int>("SourceType")
                        .HasColumnType("integer")
                        .HasColumnName("source_type");

                    b.Property<int?>("UnitType")
                        .HasColumnType("integer")
                        .HasColumnName("unit_type");

                    b.HasKey("Id")
                        .HasName("pk_inventory_movement_details");

                    b.HasIndex("MovementId")
                        .HasDatabaseName("ix_inventory_movement_details_movement_id");

                    b.ToTable("inventory_movement_details", (string)null);
                });

            modelBuilder.Entity("AgroInventory.Domain.Entities.MembershipAccessScope", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("MembershipId")
                        .HasColumnType("uuid")
                        .HasColumnName("membership_id");

                    b.Property<Guid?>("ScopeEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("scope_entity_id");

                    b.Property<int>("ScopeType")
                        .HasColumnType("integer")
                        .HasColumnName("scope_type");

                    b.HasKey("Id")
                        .HasName("pk_membership_access_scopes");

                    b.HasIndex("MembershipId", "ScopeType")
                        .HasDatabaseName("ix_membership_access_scopes_membership_id_scope_type");

                    b.ToTable("membership_access_scopes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000203"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            MembershipId = new Guid("00000000-0000-0000-0000-000000000202"),
                            ScopeType = 0
                        });
                });

            modelBuilder.Entity("AgroInventory.Domain.Entities.OpenedPackage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChemicalId")
                        .HasColumnType("uuid")
                        .HasColumnName("chemical_id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("InitialLiters")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("initial_liters");

                    b.Property<DateTimeOffset>("OpenedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opened_at");

                    b.Property<decimal>("RemainingLiters")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("remaining_liters");

                    b.Property<int>("UnitType")
                        .HasColumnType("integer")
                        .HasColumnName("unit_type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("warehouse_id");

                    b.HasKey("Id")
                        .HasName("pk_opened_packages");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_opened_packages_company_id");

                    b.HasIndex("WarehouseId")
                        .HasDatabaseName("ix_opened_packages_warehouse_id");

                    b.HasIndex("ChemicalId", "WarehouseId")
                        .HasDatabaseName("ix_opened_packages_chemical_id_warehouse_id");

                    b.ToTable("opened_packages", (string)null);
                });

            modelBuilder.Entity("AgroInventory.Domain.Entities.PackageGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChemicalId")
                        .HasColumnType("uuid")
                        .HasColumnName("chemical_id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("PackageVolumeLiters")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("package_volume_liters");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<int>("UnitType")
                        .HasColumnType("integer")
                        .HasColumnName("unit_type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("warehouse_id");

                    b.HasKey("Id")
                        .HasName("pk_package_groups");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_package_groups_company_id");

                    b.HasIndex("WarehouseId")
                        .HasDatabaseName("ix_package_groups_warehouse_id");

                    b.HasIndex("ChemicalId", "WarehouseId")
                        .HasDatabaseName("ix_package_groups_chemical_id_warehouse_id");

                    b.ToTable("package_groups", (string)null);
                });

            modelBuilder.Entity("AgroInventory.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system");

                    b.Property<bool>("IsSystemAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system_admin");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("last_name");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("boolean")
                        .HasColumnName("must_change_password");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayName = "System",
                            FirstName = "System",
                            IsSystem = true,
                            IsSystemAdmin = true,
                            LastName = "",
                            MustChangePassword = false,
                            Status = 0,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("AgroInventory.Domain.Entities.Warehouse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("number");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_warehouses");

                    b.HasIndex("CompanyId", "Number")
                        .IsUnique()
                        .HasDatabaseName("ix_warehouses_company_id_number");

                    b.ToTable("warehouses", (string)null);
                });

            modelBuilder.Entity("AgroInventory.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("AgroInventory.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_audit_logs_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AgroInventory.Domain.Entities.ChemicalCrop", b =>
                {
                    b.HasOne("AgroInventory.Domain.Entities.InventoryItem", "Chemical")
                        .WithMany("ChemicalCrops")
                        .HasForeignKey("ChemicalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chemical_crops_inventory_items_chemical_id");

                    b.HasOne("AgroInventory.Domain.Entities.Crop", "Crop")
                        .WithMany("ChemicalCrops")
                        .HasForeignKey("CropId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_chemical_crops_crops_crop_id");

                    b.Navigation("Chemical");

                    b.Navigation("Crop");
                });

            modelBuilder.Entity("AgroInventory.Domain.Entities.ChemicalDetails", b =>
                {
                    b.HasOne("AgroInventory.Domain.Entities.InventoryItem", "InventoryItem")
                        .WithOne("ChemicalDetails")
                        .HasForeignKey("AgroInventory.Domain.Entities.ChemicalDetails", "InventoryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chemical_details_inventory_items_inventory_item_id");

                    b.Navigation("InventoryItem");
                });

            modelBuilder.Entity("AgroInventory.Domain.Entities.ChemicalStockBalance", b =>
                {
                    b.HasOne("AgroInventory.Domain.Entities.InventoryItem", "Chemical")
                        .WithMany()
                        .HasForeignKey("ChemicalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chemical_stock_balances_inventory_items_chemical_id");

                    b.HasOne("AgroInventory.Domain.Entities.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_chemical_stock_balances_companies_company_id");

                    b.HasOne("AgroInventory.Domain.Entities.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_chemical_stock_balances_warehouses_warehouse_id");

                    b.Navigation("Chemical");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("AgroInventory.Domain.Entities.Company", b =>
                {
                    b.HasOne("AgroInventory.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_companies_users_created_by_user_id");
                });

            modelBuilder.Entity("AgroInventory.Domain.Entities.CompanyMembership", b =>
                {
                    b.HasOne("AgroInventory.Domain.Entities.Company", "Company")
                        .WithMany("Memberships")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_company_memberships_companies_company_id");

                    b.HasOne("AgroInventory.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_company_memberships_users_created_by_user_id");

                    b.HasOne("AgroInventory.Domain.Entities.User", "User")
                        .WithMany("Memberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_company_memberships_users_user_id");

                    b.Navigation("Company");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AgroInventory.Domain.Entities.Crop", b =>
                {
                    b.HasOne("AgroInventory.Domain.Entities.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_crops_companies_company_id");
                });

            modelBuilder.Entity("AgroInventory.Domain.Entities.Field", b =>
                {
                    b.HasOne("AgroInventory.Domain.Entities.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_fields_companies_company_id");
                });

            modelBuilder.Entity("AgroInventory.Domain.Entities.InventoryItem", b =>
                {
                    b.HasOne("AgroInventory.Domain.Entities.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_items_companies_company_id");

                    b.HasOne("AgroInventory.Domain.Entities.InventoryItem", "MergedIntoItem")
                        .WithMany()
                        .HasForeignKey("MergedIntoItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_inventory_items_inventory_items_merged_into_item_id");

                    b.Navigation("MergedIntoItem");
                });

            modelBuilder.Entity("AgroInventory.Domain.Entities.InventoryMovement", b =>
                {
                    b.HasOne("AgroInventory.Domain.Entities.InventoryItem", "Chemical")
                        .WithMany()
                        .HasForeignKey("ChemicalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_movements_inventory_items_chemical_id");

                    b.HasOne("AgroInventory.Domain.Entities.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_movements_companies_company_id");

                    b.HasOne("AgroInventory.Domain.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_movements_users_created_by_user_id");

                    b.HasOne("AgroInventory.Domain.Entities.Crop", "Crop")
                        .WithMany()
                        .HasForeignKey("CropId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_inventory_movements_crops_crop_id");

                    b.HasOne("AgroInventory.Domain.Entities.Field", "Field")
                        .WithMany()
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_inventory_movements_fields_field_id");

                    b.HasOne("AgroInventory.Domain.Entities.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_movements_warehouses_warehouse_id");

                    b.Navigation("Chemical");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Crop");

                    b.Navigation("Field");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("AgroInventory.Domain.Entities.InventoryMovementDetail", b =>
                {
                    b.HasOne("AgroInventory.Domain.Entities.InventoryMovement", "Movement")
                        .WithMany("Details")
                        .HasForeignKey("MovementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_movement_details_inventory_movements_movement_id");

                    b.Navigation("Movement");
                });

            modelBuilder.Entity("AgroInventory.Domain.Entities.MembershipAccessScope", b =>
                {
                    b.HasOne("AgroInventory.Domain.Entities.CompanyMembership", "Membership")
                        .WithMany("AccessScopes")
                        .HasForeignKey("MembershipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_membership_access_scopes_company_memberships_membership_id");

                    b.Navigation("Membership");
                });

            modelBuilder.Entity("AgroInventory.Domain.Entities.OpenedPackage", b =>
                {
                    b.HasOne("AgroInventory.Domain.Entities.InventoryItem", "Chemical")
                        .WithMany()
                        .HasForeignKey("ChemicalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_opened_packages_inventory_items_chemical_id");

                    b.HasOne("AgroInventory.Domain.Entities.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_opened_packages_companies_company_id");

                    b.HasOne("AgroInventory.Domain.Entities.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_opened_packages_warehouses_warehouse_id");

                    b.Navigation("Chemical");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("AgroInventory.Domain.Entities.PackageGroup", b =>
                {
                    b.HasOne("AgroInventory.Domain.Entities.InventoryItem", "Chemical")
                        .WithMany()
                        .HasForeignKey("ChemicalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_package_groups_inventory_items_chemical_id");

                    b.HasOne("AgroInventory.Domain.Entities.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_package_groups_companies_company_id");

                    b.HasOne("AgroInventory.Domain.Entities.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_package_groups_warehouses_warehouse_id");

                    b.Navigation("Chemical");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("AgroInventory.Domain.Entities.Warehouse", b =>
                {
                    b.HasOne("AgroInventory.Domain.Entities.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_warehouses_companies_company_id");
                });

            modelBuilder.Entity("AgroInventory.Domain.Entities.Company", b =>
                {
                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("AgroInventory.Domain.Entities.CompanyMembership", b =>
                {
                    b.Navigation("AccessScopes");
                });

            modelBuilder.Entity("AgroInventory.Domain.Entities.Crop", b =>
                {
                    b.Navigation("ChemicalCrops");
                });

            modelBuilder.Entity("AgroInventory.Domain.Entities.InventoryItem", b =>
                {
                    b.Navigation("ChemicalCrops");

                    b.Navigation("ChemicalDetails");
                });

            modelBuilder.Entity("AgroInventory.Domain.Entities.InventoryMovement", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("AgroInventory.Domain.Entities.User", b =>
                {
                    b.Navigation("Memberships");
                });
#pragma warning restore 612, 618
        }
    }
}
