// <auto-generated />
using System;
using AgroInventory.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AgroInventory.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AgroInventoryDbContext))]
    partial class AgroInventoryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AgroInventory.Domain.Entities.AppSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AutoOpenPackages")
                        .HasColumnType("boolean")
                        .HasColumnName("auto_open_packages");

                    b.Property<decimal>("LowStockThresholdLiters")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("low_stock_threshold_liters");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_app_settings");

                    b.ToTable("app_settings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            AutoOpenPackages = false,
                            LowStockThresholdLiters = 10m,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("AgroInventory.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Action")
                        .HasColumnType("integer")
                        .HasColumnName("action");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_type");

                    b.Property<string>("NewValues")
                        .HasColumnType("jsonb")
                        .HasColumnName("new_values");

                    b.Property<string>("OldValues")
                        .HasColumnType("jsonb")
                        .HasColumnName("old_values");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("Action")
                        .HasDatabaseName("ix_audit_logs_action");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_audit_logs_created_at");

                    b.HasIndex("EntityType")
                        .HasDatabaseName("ix_audit_logs_entity_type");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_audit_logs_user_id");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("AgroInventory.Domain.Entities.ChemicalCrop", b =>
                {
                    b.Property<Guid>("ChemicalId")
                        .HasColumnType("uuid")
                        .HasColumnName("chemical_id");

                    b.Property<Guid>("CropId")
                        .HasColumnType("uuid")
                        .HasColumnName("crop_id");

                    b.HasKey("ChemicalId", "CropId")
                        .HasName("pk_chemical_crops");

                    b.HasIndex("CropId")
                        .HasDatabaseName("ix_chemical_crops_crop_id");

                    b.ToTable("chemical_crops", (string)null);
                });

            modelBuilder.Entity("AgroInventory.Domain.Entities.ChemicalDetails", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("comment");

                    b.Property<Guid>("InventoryItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("inventory_item_id");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("manufacturer");

                    b.HasKey("Id")
                        .HasName("pk_chemical_details");

                    b.HasIndex("InventoryItemId")
                        .IsUnique()
                        .HasDatabaseName("ix_chemical_details_inventory_item_id");

                    b.ToTable("chemical_details", (string)null);
                });

            modelBuilder.Entity("AgroInventory.Domain.Entities.ChemicalStockBalance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChemicalId")
                        .HasColumnType("uuid")
                        .HasColumnName("chemical_id");

                    b.Property<decimal>("LooseLiters")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("loose_liters");

                    b.Property<decimal>("TotalLiters")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("total_liters");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("warehouse_id");

                    b.HasKey("Id")
                        .HasName("pk_chemical_stock_balances");

                    b.HasIndex("WarehouseId")
                        .HasDatabaseName("ix_chemical_stock_balances_warehouse_id");

                    b.HasIndex("ChemicalId", "WarehouseId")
                        .IsUnique()
                        .HasDatabaseName("ix_chemical_stock_balances_chemical_id_warehouse_id");

                    b.ToTable("chemical_stock_balances", (string)null);
                });

            modelBuilder.Entity("AgroInventory.Domain.Entities.Crop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_crops");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_crops_name");

                    b.ToTable("crops", (string)null);
                });

            modelBuilder.Entity("AgroInventory.Domain.Entities.InventoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("ItemType")
                        .HasColumnType("integer")
                        .HasColumnName("item_type");

                    b.Property<Guid?>("MergedIntoItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("merged_into_item_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_inventory_items");

                    b.HasIndex("ItemType")
                        .HasDatabaseName("ix_inventory_items_item_type");

                    b.HasIndex("MergedIntoItemId")
                        .HasDatabaseName("ix_inventory_items_merged_into_item_id");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_inventory_items_name");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_inventory_items_status");

                    b.ToTable("inventory_items", (string)null);
                });

            modelBuilder.Entity("AgroInventory.Domain.Entities.InventoryMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChemicalId")
                        .HasColumnType("uuid")
                        .HasColumnName("chemical_id");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("comment");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<Guid?>("CropId")
                        .HasColumnType("uuid")
                        .HasColumnName("crop_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<int>("MovementType")
                        .HasColumnType("integer")
                        .HasColumnName("movement_type");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<decimal?>("PackageVolumeLiters")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("package_volume_liters");

                    b.Property<int?>("PackagesQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("packages_quantity");

                    b.Property<decimal>("QuantityLiters")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("quantity_liters");

                    b.Property<int?>("UnitType")
                        .HasColumnType("integer")
                        .HasColumnName("unit_type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("warehouse_id");

                    b.HasKey("Id")
                        .HasName("pk_inventory_movements");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_inventory_movements_created_by_user_id");

                    b.HasIndex("CropId")
                        .HasDatabaseName("ix_inventory_movements_crop_id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_inventory_movements_is_deleted");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_inventory_movements_occurred_at");

                    b.HasIndex("WarehouseId")
                        .HasDatabaseName("ix_inventory_movements_warehouse_id");

                    b.HasIndex("ChemicalId", "WarehouseId")
                        .HasDatabaseName("ix_inventory_movements_chemical_id_warehouse_id");

                    b.ToTable("inventory_movements", (string)null);
                });

            modelBuilder.Entity("AgroInventory.Domain.Entities.InventoryMovementDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("MovementId")
                        .HasColumnType("uuid")
                        .HasColumnName("movement_id");

                    b.Property<decimal?>("PackageVolumeLiters")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("package_volume_liters");

                    b.Property<int?>("PackagesQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("packages_quantity");

                    b.Property<decimal>("QuantityLiters")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("quantity_liters");

                    b.Property<Guid?>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<int>("SourceType")
                        .HasColumnType("integer")
                        .HasColumnName("source_type");

                    b.Property<int?>("UnitType")
                        .HasColumnType("integer")
                        .HasColumnName("unit_type");

                    b.HasKey("Id")
                        .HasName("pk_inventory_movement_details");

                    b.HasIndex("MovementId")
                        .HasDatabaseName("ix_inventory_movement_details_movement_id");

                    b.ToTable("inventory_movement_details", (string)null);
                });

            modelBuilder.Entity("AgroInventory.Domain.Entities.OpenedPackage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChemicalId")
                        .HasColumnType("uuid")
                        .HasColumnName("chemical_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("InitialLiters")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("initial_liters");

                    b.Property<DateTimeOffset>("OpenedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opened_at");

                    b.Property<decimal>("RemainingLiters")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("remaining_liters");

                    b.Property<int>("UnitType")
                        .HasColumnType("integer")
                        .HasColumnName("unit_type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("warehouse_id");

                    b.HasKey("Id")
                        .HasName("pk_opened_packages");

                    b.HasIndex("WarehouseId")
                        .HasDatabaseName("ix_opened_packages_warehouse_id");

                    b.HasIndex("ChemicalId", "WarehouseId")
                        .HasDatabaseName("ix_opened_packages_chemical_id_warehouse_id");

                    b.ToTable("opened_packages", (string)null);
                });

            modelBuilder.Entity("AgroInventory.Domain.Entities.PackageGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChemicalId")
                        .HasColumnType("uuid")
                        .HasColumnName("chemical_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("PackageVolumeLiters")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("package_volume_liters");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<int>("UnitType")
                        .HasColumnType("integer")
                        .HasColumnName("unit_type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("warehouse_id");

                    b.HasKey("Id")
                        .HasName("pk_package_groups");

                    b.HasIndex("WarehouseId")
                        .HasDatabaseName("ix_package_groups_warehouse_id");

                    b.HasIndex("ChemicalId", "WarehouseId")
                        .HasDatabaseName("ix_package_groups_chemical_id_warehouse_id");

                    b.ToTable("package_groups", (string)null);
                });

            modelBuilder.Entity("AgroInventory.Domain.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.HasKey("Id")
                        .HasName("pk_permissions");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_permissions_code");

                    b.ToTable("permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000101"),
                            Code = "manage_settings"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000102"),
                            Code = "restore_backup"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000103"),
                            Code = "manage_users"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000104"),
                            Code = "manage_inventory"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000105"),
                            Code = "view_audit_log"
                        });
                });

            modelBuilder.Entity("AgroInventory.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_code");

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            Code = "admin",
                            DisplayName = "Администратор"
                        });
                });

            modelBuilder.Entity("AgroInventory.Domain.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_id");

                    b.HasKey("RoleId", "PermissionId")
                        .HasName("pk_role_permissions");

                    b.HasIndex("PermissionId")
                        .HasDatabaseName("ix_role_permissions_permission_id");

                    b.ToTable("role_permissions", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000101")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000102")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000103")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000104")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000105")
                        });
                });

            modelBuilder.Entity("AgroInventory.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username");

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayName = "System",
                            IsSystem = true,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Username = "system"
                        });
                });

            modelBuilder.Entity("AgroInventory.Domain.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_roles_role_id");

                    b.ToTable("user_roles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000001"),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000002")
                        });
                });

            modelBuilder.Entity("AgroInventory.Domain.Entities.Warehouse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("number");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_warehouses");

                    b.HasIndex("Number")
                        .IsUnique()
                        .HasDatabaseName("ix_warehouses_number");

                    b.ToTable("warehouses", (string)null);
                });

            modelBuilder.Entity("AgroInventory.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("AgroInventory.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_audit_logs_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AgroInventory.Domain.Entities.ChemicalCrop", b =>
                {
                    b.HasOne("AgroInventory.Domain.Entities.InventoryItem", "Chemical")
                        .WithMany("ChemicalCrops")
                        .HasForeignKey("ChemicalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chemical_crops_inventory_items_chemical_id");

                    b.HasOne("AgroInventory.Domain.Entities.Crop", "Crop")
                        .WithMany("ChemicalCrops")
                        .HasForeignKey("CropId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_chemical_crops_crops_crop_id");

                    b.Navigation("Chemical");

                    b.Navigation("Crop");
                });

            modelBuilder.Entity("AgroInventory.Domain.Entities.ChemicalDetails", b =>
                {
                    b.HasOne("AgroInventory.Domain.Entities.InventoryItem", "InventoryItem")
                        .WithOne("ChemicalDetails")
                        .HasForeignKey("AgroInventory.Domain.Entities.ChemicalDetails", "InventoryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chemical_details_inventory_items_inventory_item_id");

                    b.Navigation("InventoryItem");
                });

            modelBuilder.Entity("AgroInventory.Domain.Entities.ChemicalStockBalance", b =>
                {
                    b.HasOne("AgroInventory.Domain.Entities.InventoryItem", "Chemical")
                        .WithMany()
                        .HasForeignKey("ChemicalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chemical_stock_balances_inventory_items_chemical_id");

                    b.HasOne("AgroInventory.Domain.Entities.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_chemical_stock_balances_warehouses_warehouse_id");

                    b.Navigation("Chemical");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("AgroInventory.Domain.Entities.InventoryItem", b =>
                {
                    b.HasOne("AgroInventory.Domain.Entities.InventoryItem", "MergedIntoItem")
                        .WithMany()
                        .HasForeignKey("MergedIntoItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_inventory_items_inventory_items_merged_into_item_id");

                    b.Navigation("MergedIntoItem");
                });

            modelBuilder.Entity("AgroInventory.Domain.Entities.InventoryMovement", b =>
                {
                    b.HasOne("AgroInventory.Domain.Entities.InventoryItem", "Chemical")
                        .WithMany()
                        .HasForeignKey("ChemicalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_movements_inventory_items_chemical_id");

                    b.HasOne("AgroInventory.Domain.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_movements_users_created_by_user_id");

                    b.HasOne("AgroInventory.Domain.Entities.Crop", "Crop")
                        .WithMany()
                        .HasForeignKey("CropId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_inventory_movements_crops_crop_id");

                    b.HasOne("AgroInventory.Domain.Entities.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_movements_warehouses_warehouse_id");

                    b.Navigation("Chemical");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Crop");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("AgroInventory.Domain.Entities.InventoryMovementDetail", b =>
                {
                    b.HasOne("AgroInventory.Domain.Entities.InventoryMovement", "Movement")
                        .WithMany("Details")
                        .HasForeignKey("MovementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_movement_details_inventory_movements_movement_id");

                    b.Navigation("Movement");
                });

            modelBuilder.Entity("AgroInventory.Domain.Entities.OpenedPackage", b =>
                {
                    b.HasOne("AgroInventory.Domain.Entities.InventoryItem", "Chemical")
                        .WithMany()
                        .HasForeignKey("ChemicalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_opened_packages_inventory_items_chemical_id");

                    b.HasOne("AgroInventory.Domain.Entities.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_opened_packages_warehouses_warehouse_id");

                    b.Navigation("Chemical");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("AgroInventory.Domain.Entities.PackageGroup", b =>
                {
                    b.HasOne("AgroInventory.Domain.Entities.InventoryItem", "Chemical")
                        .WithMany()
                        .HasForeignKey("ChemicalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_package_groups_inventory_items_chemical_id");

                    b.HasOne("AgroInventory.Domain.Entities.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_package_groups_warehouses_warehouse_id");

                    b.Navigation("Chemical");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("AgroInventory.Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("AgroInventory.Domain.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_permissions_permission_id");

                    b.HasOne("AgroInventory.Domain.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_roles_role_id");

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("AgroInventory.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("AgroInventory.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_roles_role_id");

                    b.HasOne("AgroInventory.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_users_user_id");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AgroInventory.Domain.Entities.Crop", b =>
                {
                    b.Navigation("ChemicalCrops");
                });

            modelBuilder.Entity("AgroInventory.Domain.Entities.InventoryItem", b =>
                {
                    b.Navigation("ChemicalCrops");

                    b.Navigation("ChemicalDetails");
                });

            modelBuilder.Entity("AgroInventory.Domain.Entities.InventoryMovement", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("AgroInventory.Domain.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("AgroInventory.Domain.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("AgroInventory.Domain.Entities.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
